Update FUNDING.yml

diff --git a/.github/FUNDING.yml b/.github/FUNDING.yml
--- a/.github/FUNDING.yml
+++ b/.github/FUNDING.yml
@@ -1,138 +1,33 @@
-name: Build
+#!/bin/sh
 
-on: [push]
+BASE_PATH=drivers/vision/npu
+TARGET_FILE=$BASE_PATH/generated/npu-ver-info~
+NPU_GIT_LOG=`git log --oneline -5 ${BASE_PATH}|cut --bytes=-60|sed 's/[\"%]/\\\\&/g'|awk '{print "\""$0"\\\n\""}'`
+NPU_GIT_HASH=`git log --oneline -5 --format=format:%H ${BASE_PATH}|cut --bytes=-60|sed 's/[\"%]/\\\\&/g'|awk '{print "\""$0"\\\n\""}'`
+NPU_GIT_LOCAL_CHANGE="$(git diff --shortstat)"
+if [ -z "$NPU_GIT_LOCAL_CHANGE" ]
+then
+	NPU_GIT_LOCAL_CHANGE="No local change"
+fi
+STASH_DEPTH="$(git stash list | wc -l)"
+USER_INFO="$(whoami | sed 's/\\/\-/g')"
 
-env:
-  TOOLCHAIN: cruel
-  INSTALLER: yes
+# Error checking
+if [ \( -z "$NPU_GIT_LOG" \) -o \( -z "$NPU_GIT_HASH" \) -o \( -z "$USER_INFO" \) -o \( -z "$NPU_GIT_LOCAL_CHANGE" \) -o \( -z "$STASH_DEPTH" \) ]
+then
+	echo "An error occured during build info gathering." >&2
+	exit 16
+fi
 
-jobs:
-  build:
-    runs-on: ubuntu-22.04
+BUILD_INFO="$USER_INFO@$(hostname) / Build on $(date --rfc-3339='seconds')"
 
-    strategy:
-      fail-fast: false
-      matrix:
-        model: [ "G970F,G973F,G975F", "N970F,N975F" ]
-
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-python@v2
-        with:
-          python-version: '3.7'
-
-      - name: Install dependencies
-        env:
-          DEBIAN_FRONTEND: noninteractive
-        run: sudo apt-get install -y -qq libtinfo5 ccache
-
-
-      - name: Disable compression in ccache and set ccache path
-        run: ccache -o compression=false -o cache_dir=$HOME/.ccache
-
-      - name: Prepare ccache timestamp
-        id: ccache_timestamp
-        run: |
-          echo "::set-output name=FULL_DATE::$(date +'%Y-%m-%d')"
-          echo "::set-output name=MONTH_DATE::$(date +'%Y-%m')"
-
-      - name: Create cache key from ${{ matrix.model }}
-        id: ccache_model_key
-        run: echo "::set-output name=KEY::$( echo ${{ matrix.model }} | tr ',' '_' )"
-
-      - name: Cache ccache files
-        uses: actions/cache@v3
-        with:
-          path: ~/.ccache
-          key: ccache-${{ env.TOOLCHAIN }}-${{ steps.ccache_model_key.outputs.KEY }}-${{ steps.ccache_timestamp.outputs.FULL_DATE }}
-          restore-keys: |
-            ccache-${{ env.TOOLCHAIN }}-${{ steps.ccache_model_key.outputs.KEY }}-${{ steps.ccache_timestamp.outputs.MONTH_DATE }}
-            ccache-${{ env.TOOLCHAIN }}-${{ steps.ccache_model_key.outputs.KEY }}-
-            ccache-${{ env.TOOLCHAIN }}-
-
-      - name: Kernel Configure
-        run: |
-          set -e -o pipefail
-          ./cruelbuild config                    \
-                       model=${{ matrix.model }} \
-                       name="Cruel-v4.5"         \
-                       toolchain=$TOOLCHAIN      \
-                       +magisk                   \
-                       +nohardening              \
-                       +ttl                      \
-                       +wireguard                \
-                       +cifs                     \
-                       +sdfat                    \
-                       +ntfs                     \
-                       +force_dex_wqhd           \
-                       +morosound                \
-                       +boeffla_wl_blocker       \
-          2>&1 | tee config.info
-
-      - name: Install gcc-aarch64-linux-gnu
-        if: env.TOOLCHAIN == 'system-gcc' || env.TOOLCHAIN == 'system-clang'
-        env:
-          DEBIAN_FRONTEND: noninteractive
-        run: sudo apt-get install -y -qq gcc-aarch64-linux-gnu
-      - name: Install clang
-        if: env.TOOLCHAIN == 'system-clang'
-        env:
-          DEBIAN_FRONTEND: noninteractive
-        run: sudo apt-get install -y -qq llvm lld clang
-      - name: Deploy Toolchain
-        if: env.TOOLCHAIN != 'system-gcc' && env.TOOLCHAIN != 'system-clang'
-        run: git clone --depth 1 -j $(nproc) --branch $TOOLCHAIN --single-branch https://github.com/CruelKernel/samsung-exynos9820-toolchain toolchain
-
-      - name: Kernel Build
-        run: ./cruelbuild :build
-
-      - name: Install mkbootimg
-        run: |
-          wget -q https://android.googlesource.com/platform/system/tools/mkbootimg/+archive/refs/heads/master.tar.gz -O - | tar xzf - mkbootimg.py gki
-          chmod +x mkbootimg.py
-          sudo mv mkbootimg.py /usr/local/bin/mkbootimg
-          sudo mv gki $(python -c 'import site; print(site.getsitepackages()[0])')
-      - name: Install mkdtboimg
-        run: |
-          wget -q https://android.googlesource.com/platform/system/libufdt/+archive/refs/heads/master.tar.gz -O - | tar --strip-components 2 -xzf - utils/src/mkdtboimg.py
-          chmod +x mkdtboimg.py
-          sudo mv mkdtboimg.py /usr/local/bin/mkdtboimg
-      - name: Install avbtool
-        run: |
-          wget -q https://android.googlesource.com/platform/external/avb/+archive/refs/heads/master.tar.gz -O - | tar xzf - avbtool.py
-          chmod +x avbtool.py
-          sudo mv avbtool.py /usr/local/bin/avbtool
-
-      - name: Create CruelKernel images for ${{ matrix.model }}
-        run: ./cruelbuild :mkimg
-      - name: Create CruelKernel installer for ${{ matrix.model }}
-        if: env.INSTALLER == 'yes'
-        run: ./cruelbuild :pack
-
-      - name: Avoid Double Zipping in Installer
-        if: env.INSTALLER == 'yes'
-        run: |
-          mkdir -p installer && cd installer
-          unzip ../CruelKernel.zip
-      - name: Upload Kernel Zip
-        if: env.INSTALLER == 'yes'
-        uses: actions/upload-artifact@v2
-        with:
-          name: CruelKernel-${{ matrix.model }}
-          path: installer/*
-          if-no-files-found: error
-      - name: Upload Kernel Images
-        if: env.INSTALLER != 'yes'
-        uses: actions/upload-artifact@v2
-        with:
-          name: CruelKernel-${{ matrix.model }}
-          path: '*.img'
-          if-no-files-found: error
-
-      - name: Upload Kernel Info
-        uses: actions/upload-artifact@v2
-        with:
-          name: ConfigurationInfo-${{ matrix.model }}
-          path: config.*
-          if-no-files-found: error
-
+cat > $TARGET_FILE << ENDL
+const char *npu_git_log_str =
+${NPU_GIT_LOG}
+"${NPU_GIT_LOCAL_CHANGE} / Stash depth=${STASH_DEPTH}";
+const char *npu_git_hash_str =
+${NPU_GIT_HASH}
+"${NPU_GIT_LOCAL_CHANGE} / Stash depth=${STASH_DEPTH}";
+const char *npu_build_info =
+"${BUILD_INFO}";
+ENDL
